import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline": "#717976",
        "inverse-on-surface": "#e7f2fe",
        "on-primary-fixed-variant": "#2d4c46",
        "on-primary-fixed": "#00201b",
        "surface-bright": "#f7f9ff",
        "secondary-fixed": "#ffdbce",
        "on-primary-container": "#1b3b35",
        "surface-container-highest": "#d9e4ef",
        "primary-fixed-dim": "#accec5",
        "primary": "#45645e",
        "on-tertiary-container": "#4d2d26",
        "tertiary-fixed": "#ffdad2",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "surface-container-low": "#ecf4ff",
        "on-secondary-fixed": "#380d00",
        "inverse-primary": "#accec5",
        "on-secondary-fixed-variant": "#6f3720",
        "on-surface": "#131d25",
        "tertiary-fixed-dim": "#ecbbb1",
        "on-error": "#ffffff",
        "on-surface-variant": "#414846",
        "surface": "#f7f9ff",
        "outline-variant": "#c1c8c5",
        "secondary-fixed-dim": "#ffb59a",
        "on-secondary-container": "#793f27",
        "tertiary": "#7b554d",
        "on-tertiary-fixed": "#2f140e",
        "inverse-surface": "#28313a",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container": "#e5effb",
        "on-background": "#131d25",
        "surface-tint": "#45645e",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#603e36",
        "secondary": "#8c4e35",
        "primary-fixed": "#c7eae1",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#d1dbe7",
        "secondary-container": "#ffad8f",
        "primary-container": "#84a59d",
        "surface-variant": "#d9e4ef",
        "tertiary-container": "#c1948a",
        "surface-container-high": "#dfe9f5",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        md: "16px",
        xl: "32px",
        lg: "24px",
        "margin-desktop": "40px",
        "2xl": "48px",
        sm: "8px",
        base: "4px",
        "3xl": "64px",
        gutter: "24px",
        "margin-mobile": "16px",
        xs: "4px",
      },
      fontFamily: {
        "body-md": ["var(--font-dm-sans)"],
        "label-sm": ["var(--font-dm-sans)"],
        "button": ["var(--font-dm-sans)"],
        "headline-md": ["var(--font-dm-sans)"],
        "headline-xl": ["var(--font-dm-sans)"],
        "headline-lg-mobile": ["var(--font-dm-sans)"],
        "headline-xl-mobile": ["var(--font-dm-sans)"],
        "label-md": ["var(--font-dm-sans)"],
        "body-lg": ["var(--font-dm-sans)"],
        "headline-lg": ["var(--font-dm-sans)"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        button: ["15px", { lineHeight: "20px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["26px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-xl-mobile": ["32px", { lineHeight: "38px", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
      },
      boxShadow: {
        soft: "0px 12px 32px rgba(113, 121, 118, 0.08)",
        "inner-soft": "inset 0px 1px 3px rgba(113, 121, 118, 0.1)",
        "glow-primary": "0 0 0 4px rgba(132, 165, 157, 0.2)",
      },
    },
  },
  plugins: [],
};
export default config;
